# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx6G
# Fabric Properties
minecraft_version=1.21.3
yarn_mappings=1.21.3+build.2
loader_version=0.16.7
# Mod Properties
mod_version = 1.4.4
maven_group = essentialaddons
# Dependencies
carpet_version=1.4.158
lithium_version=mc1.21-0.13.0
fabric_version=0.106.1+1.21.3
minecraft_dependency=1.21.x

