# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx6G
# Fabric Properties
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.1
loader_version=0.16.9
# Mod Properties
mod_version = 1.4.5
maven_group = essentialaddons
# Dependencies
carpet_version=1.4.160
lithium_version=mc1.21.3-0.14.2
fabric_version=0.110.5+1.21.4
minecraft_dependency=1.21.x

