# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx6G
# Fabric Properties
minecraft_version=1.20.5
yarn_mappings=1.20.5+build.1
loader_version=0.15.10
# Mod Properties
mod_version = 1.4.1
maven_group = essentialaddons
# Dependencies
carpet_version=8639fa9d957bc41d205280017ffe325093c924ad
lithium_version=98a10fbeeaf72a1b1162f5fe6ec8315df3e9caa5
fabric_version=0.97.6+1.20.5
minecraft_dependency=1.20.x

